
// THIS FILE IS AUTOGENERATED WHEN PAGES ARE UPDATED
import { lazy } from "react";
import { RouteObject } from "react-router-dom";


import { UserGuard } from "app";


import { StackHandlerRoutes, LoginRedirect } from "app/auth";


const About = lazy(() => import("./pages/About.tsx"));
const Analytics = lazy(() => import("./pages/Analytics.tsx"));
const App = lazy(() => import("./pages/App.tsx"));
const BlogPost = lazy(() => import("./pages/BlogPost.tsx"));
const Categories = lazy(() => import("./pages/Categories.tsx"));
const Contact = lazy(() => import("./pages/Contact.tsx"));
const CreatePost = lazy(() => import("./pages/CreatePost.tsx"));
const Dashboard = lazy(() => import("./pages/Dashboard.tsx"));
const Drafts = lazy(() => import("./pages/Drafts.tsx"));
const EditPost = lazy(() => import("./pages/EditPost.tsx"));
const Profile = lazy(() => import("./pages/Profile.tsx"));
const Search = lazy(() => import("./pages/Search.tsx"));
const Settings = lazy(() => import("./pages/Settings.tsx"));
const Tags = lazy(() => import("./pages/Tags.tsx"));

export const userRoutes: RouteObject[] = [

	{ path: "/auth/redirect", element: <LoginRedirect />},
	{ path: "/auth/*", element: <StackHandlerRoutes />},
	{ path: "/about", element: <About />},
	{ path: "/analytics", element: <UserGuard><Analytics /></UserGuard>},
	{ path: "/", element: <App />},
	{ path: "/blog-post", element: <BlogPost />},
	{ path: "/blogpost", element: <BlogPost />},
	{ path: "/categories", element: <Categories />},
	{ path: "/contact", element: <Contact />},
	{ path: "/create-post", element: <UserGuard><CreatePost /></UserGuard>},
	{ path: "/createpost", element: <UserGuard><CreatePost /></UserGuard>},
	{ path: "/dashboard", element: <UserGuard><Dashboard /></UserGuard>},
	{ path: "/drafts", element: <UserGuard><Drafts /></UserGuard>},
	{ path: "/edit-post", element: <UserGuard><EditPost /></UserGuard>},
	{ path: "/editpost", element: <UserGuard><EditPost /></UserGuard>},
	{ path: "/profile", element: <UserGuard><Profile /></UserGuard>},
	{ path: "/search", element: <Search />},
	{ path: "/settings", element: <UserGuard><Settings /></UserGuard>},
	{ path: "/tags", element: <Tags />},

];
